### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

Better be on the safe side...

### CODE REVIEW

**Review by cpoile — DISMISSED** [review]
I'm fine with it, I'm just wondering if this goes against the whole pinned packages and shas thing that sec/sre/delivery wants us to move towards? Maybe its ok considering its the build container?

**Comment by streamer45** [comment]
> I'm fine with it, I'm just wondering if this goes against the whole pinned packages and shas thing that sec/sre/delivery wants us to move towards? Maybe its ok considering its the build container?

This is the actual runner. I mean, we could bump the docker image as an alternative but either way once we ship an image it's done, whatever packages are in there will be stuck at their versions. So it's more of a question of defining versions at build time vs statically through the base image tag. Maybe the latter would be more stable so we could do that instead.

**Comment by streamer45** [comment]
Same on this side, bumped the image and unified so it's the same base (albeit the slim version) as the one used in recorder.

**Review by cpoile — APPROVED** [review]
👍

**Pull request merged**
